//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUMMInjector.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WUMMInjector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all {
            get {
                object obj = ResourceManager.GetObject("all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio {
            get {
                object obj = ResourceManager.GetObject("audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CDecrypt {
            get {
                object obj = ResourceManager.GetObject("CDecrypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark_16 {
            get {
                object obj = ResourceManager.GetObject("checkmark-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CNUSPacker {
            get {
                object obj = ResourceManager.GetObject("CNUSPacker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a var content = JSON.parse(contentJSON);
        ///
        ///function loadRoot() {
        ///	loadFolder(content.foldername, &apos;all&apos;);
        ///}
        ///
        ///function loadFolder(path, contentType) {
        ///	document.getElementById(&apos;content&apos;).style.marginLeft = &apos;192px&apos;;
        ///	document.getElementById(&apos;menu&apos;).style.display = &apos;inherit&apos;;
        ///	
        ///	if (contentType == &apos;all&apos;) {
        ///		var menu = &apos;&lt;li id=&quot;menu_all&quot; class=&quot;menu_active&quot;&gt;&lt;a href=&quot;#&quot; onclick=&quot;loadFolder(\&apos;&apos; + path + &apos;\&apos;, \&apos;all\&apos;)&quot;&gt;&lt;img width=&quot;192&quot; height=&quot;192&quot; src=&quot;all.png&quot; /&gt;&lt;/a&gt;&lt;/li&gt;&apos;;
        ///		menu += &apos;&lt;li id=&quot;menu_video [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string contentLoaders {
            get {
                return ResourceManager.GetString("contentLoaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;contentJSON.js&quot;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body onload=&quot;loadRoot()&quot;&gt;
        ///		&lt;ul id=&quot;menu&quot;&gt;
        ///		&lt;/ul&gt;
        ///		&lt;div id=&quot;content&quot;&gt;
        ///		&lt;/div&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;contentLoaders.js&quot;&gt;&lt;/script&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] libeay32 {
            get {
                object obj = ResourceManager.GetObject("libeay32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a body {
        ///	background-color: #181818;
        ///	margin: 0;
        ///	padding: 0;
        ///}
        ///
        ///#content video {
        ///	background-color: #181818;
        ///	width: 100%;
        ///	height: 100%;
        ///	margin: 0;
        ///	padding: 0;
        ///	position: fixed;
        ///}
        ///
        ///#image_bg {
        ///	background-color: #181818;
        ///	/*border: 1px solid blue;*/
        ///	position: absolute;
        ///	margin: 0;
        ///	padding: 0;
        ///}
        ///
        ///#image {
        ///	/*border: 1px solid red;*/
        ///	position: absolute;
        ///	margin: 0;
        ///	padding: 0;
        ///}
        ///
        ///#audio {
        ///	width: 99%;
        ///	height: 35px;
        ///	margin: 0;
        ///	padding: 0;
        ///}
        ///
        ///#menu {
        ///	list-style-ty [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_mark_16 {
            get {
                object obj = ResourceManager.GetObject("x-mark-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
